### ISSUE TITLE
Cannot get data from zabbix agent

### ISSUE THREAD

**Issue by zeyingli** [RichardKav/zabbix-nvidia-smi-integration#1]
Error reason for "12.33.243.26:gpu.free" changed: Received value [561658905890589058905890] is not suitable for value type [Numeric (float)]

**Comment by zeyingli** [comment]
Server and agent both using 3.0 Version.

**Comment by RichardKav** [comment]
Going from the information you have given me it looks like there is a issue with the database that the Zabbix server is using: [https://www.zabbix.com/forum/showthread.php?t=55758](https://www.zabbix.com/forum/showthread.php?t=55758).

Similar bugs seem to have been reported in Zabbix before such as:

[https://support.zabbix.com/browse/ZBX-11213](https://support.zabbix.com/browse/ZBX-11213)
[https://support.zabbix.com/browse/ZBX-9665](https://support.zabbix.com/browse/ZBX-9665)

I'd recommend reading these and applying any patches to the Zabbix server that are available.
