### ISSUE TITLE
be simple

### ISSUE THREAD

**Issue by masikmos** [RichardKav/zabbix-nvidia-smi-integration#3]
do it like that, it is be simple

```
UserParameter=nvsmi-gpu[*],nvidia-smi --query-gpu=$1 --format=csv,noheader,nounits -i 0

UserParameter=nvsmi-compute-apps[*],nvidia-smi --query-compute-apps=$1 --format=csv,noheader,nounits -i 0

UserParameter=nvsmi-retired-pages[*],nvidia-smi --query-retired-pages=$1 --format=csv,noheader,nounits -i 0

UserParameter=nvsmi-accounted-apps[*],nvidia-smi --query-accounted-apps=$1 --format=csv,noheader,nounits -i 0

UserParameter=nvsmi-supported-clocks[*],nvidia-smi --query-supported-clocks=$1 --format=csv,noheader,nounits -i 0
```

**Comment by woyteck1** [comment]
I've created a discovery for GPUs using the agent.
It can discover as many GPUs as you have in the system and create relevant Graphs/Items.
I'd like to add it to here, together wit XML.

**Comment by RichardKav** [comment]
I think this could be useful to many people and here seems like the best place for any enhancement like the one you suggest.

I'd be willing to upload any code, or pull any changes in from a fork of the repository.

**Comment by woyteck1** [comment]
Forked, but I will still be working on it.

**Comment by RichardKav** [comment]
A version that copes with multiple GPUs has been implemented at: [plambe/zabbix-nvidia-smi-multi-gpu](https://github.com/plambe/zabbix-nvidia-smi-multi-gpu). Hope this helps.
