### ISSUE TITLE
nvidia-smi is not recognized

### ISSUE THREAD

**Issue by RabanserD** [RichardKav/zabbix-nvidia-smi-integration#5]
Hi,

I'm getting this error when I try to use the template:
Value "'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file." of type "string" is not suitable for value type "Numeric (float)"

What I did:
1. Added the template to zabbix
2. Assigned it to a host
3. Added C:\Program Files\NVIDIA Corporation\NVSMI to the PATH var on the Windows Hosts
4. Added the UserParameters to the Zabbix conf File
5. Restarted Zabbix Service / rebooted the entire windows host

Zabbix:
![zabb](https://user-images.githubusercontent.com/27270013/50154813-c0096000-02ca-11e9-8845-28a59296ed68.png)

Host:
![cmd](https://user-images.githubusercontent.com/27270013/50154831-c8619b00-02ca-11e9-8c27-7e90de9a250c.png)

Host conf:
```
### NVidia GPU
#   https://share.zabbix.com/cat-server-hardware/other/nvidia-smi-integration
UserParameter=gpu.temp,nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits -i 0
UserParameter=gpu.memtotal,nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits -i 0
UserParameter=gpu.used,nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i 0
UserParameter=gpu.free,nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits -i 0
UserParameter=gpu.fanspeed,nvidia-smi --query-gpu=fan.speed --format=csv,noheader,nounits -i 0
UserParameter=gpu.utilisation,nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits -i 0
UserParameter=gpu.power,nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits -i 0
```
Agent Log:
```
  8692:20181218:084322.380 Zabbix Agent stopped. Zabbix 4.0.0 (revision 85308).
  8324:20181218:084326.055 Starting Zabbix Agent [Servername]. Zabbix 4.0.0 (revision 85308).
  8324:20181218:084326.055 **** Enabled features ****
  8324:20181218:084326.056 IPv6 support:          YES
  8324:20181218:084326.056 TLS support:           YES
  8324:20181218:084326.057 **************************
  8324:20181218:084326.057 using configuration file: C:\Zabbix\conf\zabbix_agentd.win.conf
  8324:20181218:084326.060 agent #0 started [main process]
  2960:20181218:084326.061 agent #2 started [listener #1]
  6752:20181218:084326.062 agent #4 started [listener #3]
  8464:20181218:084326.062 agent #1 started [collector]
  9896:20181218:084326.063 agent #5 started [active checks #1]
  1592:20181218:084326.063 agent #3 started [listener #2]
```
Info:
Server: Zabbix 4.0.2
Win Agent: 4.0.0 (amd64)

Did I forget something or is that a bug?

**Comment by RichardKav** [comment]
Hi RabanserD,

I've seen this issue before in regards to it not recognising white space correctly in the command to nvidia-smi. I'd recommend using double slashes such as: "d:\\my path" or a path such as: "C:\progra~1\" in order to make sure the nvidia-smi application name is resolved correctly.

A user agent expressions such as the one below should work correctly.

UserParameter=gpu.power,"C:\progra~1\NVIDIA Corporation\NVSMI\nvidia-smi.exe" --query-gpu=power.draw --format=csv,noheader,nounits -i 0

The issue was originally discussed at: https://share.zabbix.com/cat-server-hardware/nvidia-smi-integration. Other Zabbix related issues relating to spacing was also discussed at: www.zabbix.com/forum/showthread.php?t=18220.

**Comment by RabanserD** [comment]
Hi @RichardKav ,

thanks!! That fixed it. I could have thought of that earlier.

My new windows conf:
```
### NVidia GPU
#   https://share.zabbix.com/cat-server-hardware/other/nvidia-smi-integration
UserParameter=gpu.temp,"C:\progra~1\NVIDIA Corporation\NVSMI\nvidia-smi.exe" --query-gpu=temperature.gpu --format=csv,noheader,nounits -i 0
UserParameter=gpu.memtotal,"C:\progra~1\NVIDIA Corporation\NVSMI\nvidia-smi.exe" --query-gpu=memory.total --format=csv,noheader,nounits -i 0
UserParameter=gpu.used,"C:\progra~1\NVIDIA Corporation\NVSMI\nvidia-smi.exe" --query-gpu=memory.used --format=csv,noheader,nounits -i 0
UserParameter=gpu.free,"C:\progra~1\NVIDIA Corporation\NVSMI\nvidia-smi.exe" --query-gpu=memory.free --format=csv,noheader,nounits -i 0
UserParameter=gpu.fanspeed,"C:\progra~1\NVIDIA Corporation\NVSMI\nvidia-smi.exe" --query-gpu=fan.speed --format=csv,noheader,nounits -i 0
UserParameter=gpu.utilisation,"C:\progra~1\NVIDIA Corporation\NVSMI\nvidia-smi.exe" --query-gpu=utilization.gpu --format=csv,noheader,nounits -i 0
UserParameter=gpu.power,"C:\progra~1\NVIDIA Corporation\NVSMI\nvidia-smi.exe" --query-gpu=power.draw --format=csv,noheader,nounits -i 0
```
