### ISSUE TITLE
Getting [no data] from zabbix agent

### ISSUE THREAD

**Issue by nilbante** [RichardKav/zabbix-nvidia-smi-integration#6]
Hi,

I'm getting [no data] for all Items

Ran below steps for configuration.

1. Imported template to zabbix server
2. Assigned to GPU host (zabbix agent)
3. Added below lines to zabbix agent conf file.
UserParameter=gpu.temp,nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits -i 0
UserParameter=gpu.memtotal,nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits -i 0
UserParameter=gpu.used,nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i 0
UserParameter=gpu.free,nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits -i 0
UserParameter=gpu.fanspeed,nvidia-smi --query-gpu=fan.speed --format=csv,noheader,nounits -i 0
UserParameter=gpu.utilisation,nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits -i 0
UserParameter=gpu.power,nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits -i 0

4. Restarted zabbix services on server and agent.

![image](https://user-images.githubusercontent.com/57524461/72974154-90455980-3df4-11ea-8aca-0ca26d7e28b0.png)

![image](https://user-images.githubusercontent.com/57524461/72974272-bc60da80-3df4-11ea-81ce-7504d675c280.png)

I am able to get data when I ran manual steps.
 nvidia-smi --query-gpu=utilization.memory,memory.total,memory.free,memory.used --format=csv
utilization.memory [%], memory.total [MiB], memory.free [MiB], memory.used [MiB]
0 %, 16130 MiB, 16130 MiB, 0 MiB
0 %, 16130 MiB, 16130 MiB, 0 MiB
0 %, 16130 MiB, 16130 MiB, 0 MiB
0 %, 16130 MiB, 16130 MiB, 0 MiB

Any hint to fix issue.

**Comment by RichardKav** [comment]
Hi,

Overall from what you've said it sounds like your on the right lines. 

It might be one of two issues: 
1) communication issues between the Zabbix agent and the server installation
2) or that the agent isn't running, or is misconfigured

A few things I'd check:

- Are any other agent values been sent to the server? cpu data for example. This helps to check to see if the agent is configured correctly.
- In the list of hosts does it show that the agent is sending data to the server i.e. are there any network issues.
- Finally, are there any logs either on the server or on the agent side giving any further hints?

**Comment by nilbante** [comment]
I am able to get data for CPU, filesystem etc..

![image](https://user-images.githubusercontent.com/57524461/72995372-cb5c8280-3e1e-11ea-9016-524c9fafebef.png)  
I checked log but not able to see anything interesting. Hope /var/log/zabbix/zabbix_agentd.log  is correct one

**Comment by RichardKav** [comment]
That's the correct log for agents yes. If there is no sign of issues on the agent side is there anything in the log server side?

It's usually in a location such as: /var/log/zabbix/zabbix_server.log

A tutorial on extending Zabbix agents can be found at following URL, which might help with general guidance on the process just incase something is missing: https://www.zabbix.com/documentation/3.4/manual/config/items/userparameters/extending_agent

**Comment by nilbante** [comment]
zabbix_agentd -t gpu.memtotal
gpu.memtotal                                  [t|16130]
 zabbix_agentd -t gpu.used
gpu.used                                      [t|0]
 zabbix_agentd -t gpu.free
gpu.free                                      [t|16130]

Nothing wrong at agent side.

In server  log,  there is below message
30806:20200127:003008.390 cannot send list of active checks to "*****": host ************** not found
 30809:20200127:003009.336 cannot send list of active checks to "********": host ******** not found
 30808:20200127:003036.239 cannot send list of active checks to "********": host [******** not found
 30806:20200127:003130.199 cannot send list of active checks to "********": host******** not found
 30811:20200127:003208.495 cannot send list of active checks to "********": host ******** not found
 
But I am getting data from all hosts (like FileSystem, CPU, Memory etc..). Only for nvidia template, getting no data

**Comment by RichardKav** [comment]
Hiya,

Looks like we are getting close to fixing the issue now. This error occurs because the server cannot resolve the agent's/GPU host's name/IP address. The next check I'd do is as follows. 

On the GPU host run the following command:

`zabbix_get -s 127.0.0.1 -k agent.hostname`

I'd compare the output of this command with the one you have on the Zabbix Server frontend page under the "Hostname" (not the Visible name) and make sure it matches. Note: that the hostname is case-sensitive.

If the name does match, then I'd make sure the server can resolve the GPU host's name, i.e. using ping etc. If not add it to the host file.

A similar issue can be found in the following form (I'll share the link here as a reference): https://www.zabbix.com/forum/zabbix-help/49843-error-cannot-send-list-of-active-checks-to-x-x-x-x-host-saflok-pc-not-found.

**Comment by nilbante** [comment]
After running  zabbix_get -s 127.0.0.1 -k agent.hostname getting below output.
zabbix_get [95153]: Check access restrictions in Zabbix agent configuration

I don't think active checks is the issue as I am getting data for FileSystem, CPU, Memory for all hosts and this type of error is for all hosts.
I am able to ping server hostname from agent and from server agent hostname.

**Comment by nilbante** [comment]
Now I can see, nvidia specific items moved to not supported and there is error as "Value "sh: /usr/bin/nvidia-smi: Permission denied" of type "string" is not suitable for value type "Numeric (float)"

**Comment by RichardKav** [comment]
Do all the commands in their raw form (e.g. see below) return a number on your setup? i.e. no errors such as "Permission denied" ??  It's essential that the output can be parsed as a number, without units or other stuff.

nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits -i 0
nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits -i 0
nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i 0
nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits -i 0
nvidia-smi --query-gpu=fan.speed --format=csv,noheader,nounits -i 0
nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits -i 0
nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits -i 0

and what is the output of using [zabbix_get](https://www.zabbix.com/documentation/4.0/manpages/zabbix_get) i.e. with a command such as:

zabbix_get -s <gpu_node_ip> -k gpu.temp            

Note: this command is applicable to the others such as gpu.temp, gpu.used, gpu.fanspeed, gpu.power etc.

**Comment by nilbante** [comment]
nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits -i 0
16130
 nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i 0
0
 nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits -i 0
0
 nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits -i 0
16130

zabbix_get -s <Entered_Actual_GPU_node_IP> -k gpu.temp
zabbix_get [30005]: Check access restrictions in Zabbix agent configuration

**Comment by RichardKav** [comment]
The permission issues look to be associated with active server checks. I'd recommend either:
1) making the scraping of graphics card values passive.
2) correctly configure the active server values in the config.

e.g. https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/40943-howwwww-to-configure-server-active-check

**Comment by nilbante** [comment]
I am able to fix by running setenforce 0. Look like we have to set selinux as permissive on agent to get gpu specific data. Is this correct?

**Comment by RichardKav** [comment]
"setenforce 0" from what I can [gather](https://linuxize.com/post/how-to-disable-selinux-on-centos-7/), temporarily disables some of SELinux's security policies.  Permissive mode as I understand is used for debugging and policy development (see: [link](http://selinuxproject.org/page/Guide/Mode)), so If this suits your purposes then I'm sure it will be fine. 

I might recommend looking further into how SELinux can be configured so that it doesn't block Zabbix agents from executing the nvidia-smi command/correctly sending the data, but it is not my area of expertise.

**Comment by nilbante** [comment]
Yes, I am looking to fix this without disabling selinux. We need to disable selinux  to run nvidia-smi specific command as I am able to run  other custom commands. I'll open a issue in Zabbix forum to debug further. Thank you all your help and quick reply.
